### PR TITLE
Create and implement factory object

### PR DESCRIPTION
**Pull request by ScheepersDev23**

### CODE REVIEW

**Comment by ScheepersDev23** [comment]
Codacy didn't provide issues here, but issues can be found [here.](https://www.codacy.com/app/charltheron26/Abstract-VM/pullRequest?prid=769360)

The enum issue, it has multiple spaces\tabs for readability, I think that setting should be changed\updated.

Not so sure what it wants from me in the other 2 issues as no description is privided.

**Comment by charl26** [comment]
Fronco We need to have a chat on Monday i might of been able to figure out a better way to handle the validation Craig was looking at an example that if you use a map with the keys being the  commands and you can compare against the map if it exists

**Comment by ScheepersDev23** [comment]
Haven't we talked about this where a map won't work for this?

**Comment by charl26** [comment]
it will if i passed you vector of the words instead of the the whole string then you compere the first element against the map keys

**Pull request closed without merging**
